import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { MemoryStore } from './store.js';
import { Memory, MEMORY_FILE_BY_TYPE, MEMORY_TYPES, TYPE_HEADINGS } from './types.js';

function renderMemory(m: Memory): string {
  const files = m.refs.filter((r) => r.refType === 'file').map((r) => `\`${r.refValue}\``);
  const commit = m.refs.find((r) => r.refType === 'commit');
  const branch = m.refs.find((r) => r.refType === 'branch');
  const lines = [
    `### ${m.title}`,
    '',
    `- **id:** ${m.id}`,
    `- **severity:** ${m.severity} · **confidence:** ${m.confidence} · **status:** ${m.status}`,
    `- **recorded:** ${m.createdAt.slice(0, 10)} by ${m.createdBy}`,
  ];
  if (files.length) lines.push(`- **files:** ${files.join(', ')}`);
  if (commit) lines.push(`- **commit:** ${commit.refValue.slice(0, 10)}${branch ? ` (${branch.refValue})` : ''}`);
  lines.push('', m.body.trim(), '');
  return lines.join('\n');
}

/**
 * Render all memories of each type to their human-readable markdown file.
 * One-way: DB is canonical, markdown is a committed, PR-reviewable view.
 */
export function renderMarkdown(store: MemoryStore): string[] {
  const written: string[] = [];
  for (const type of MEMORY_TYPES) {
    const memories = store
      .list({ type })
      .filter((m) => m.status === 'active' || m.status === 'stale');
    const file = join(store.dir, MEMORY_FILE_BY_TYPE[type]);
    const header = [
      `# ${TYPE_HEADINGS[type]}`,
      '',
      '<!-- Generated by memini (`pm`). DB is canonical: edit via `pm edit <id>`, not by hand. -->',
      '',
    ].join('\n');
    const body = memories.length
      ? memories.map(renderMemory).join('\n---\n\n')
      : '_No memories recorded yet._\n';
    writeFileSync(file, header + body);
    written.push(file);
  }
  return written;
}
